"""empty message

Revision ID: 54666c75a674
Revises: 3494ae6e4039
Create Date: 2023-12-05 19:55:18.013363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54666c75a674'
down_revision: Union[str, None] = '3494ae6e4039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
